name: assignment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0' # Updated to a more common constraint, adjust if needed

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.15 # <--- MOVED HERE (ensure correct version if you want latest)
  google_fonts: ^6.1.0
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Or your preferred version

flutter:
  uses-material-design: true
  assets:
    - assets/images/
